name: 'Doxygen html generate'
description: 'Generate documentation on a commented project using doxygen'
inputs:
  cpp-directory:
    description: 'cpp Directory'
    required: true
    default: './'
  doxyfile-path:
    description: 'Path to Doxyfile'
    required: true
    default: './Doxyfile'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.cpp-directory }}
    - ${{ inputs.doxyfile-path }}
