on: [push]

jobs:
  generate_doxygen_job:
    runs-on: ubuntu-latest
    name: Generate documentation using doxygen
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: doxygen
        uses: ./
        with:
          doxyfile-path: 'cpp/Doxyfile'
      - name: Archive production artifacts
        uses: actions/upload-artifact@v1
        with:
          name: doxygen-documentation
          path: html
