on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Generate documentation using doxygen
    steps:
      # このリポジトリのプライベートアクションを使うには、リポジトリをチェックアウトしなければならない
      - name: Checkout
        uses: actions/checkout@v2
      - name: doxygen
        uses: ./
      - name: Archive production artifacts
        uses: actions/upload-artifact@v1
        with:
          name: doxygen-documentation
          path: html
